language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
script: gradle publish
env:
  global:
    secure: 80d/HeQTDSFs2X2/j9IwdXwUExCVYsd/NyeyyOzQ3TGFWxV+lLdrTERGhJD1KnmXZyZ3hHnzEDS5LzRlTT0SNaa22rS2zx8YysIPOUZli0gS9u/lOdTP3Qy/KDva7Ytf3dBdpX8otM4QC3m+IDVvHokY9oWVkWX1JHR9OF3mr9Zi/BfkkLMCi50MhufBqyPdK1oetqMkxhLWKOnBtkxFJrtYi7lLUclbe60gjtJI5tPnGHbYAjMo7IRs1vL5xZdyhiMXOaobPoyEiaOfQTUFRljiWgQ17Xok6IUwKGJF/kmkIGMGcA7KhX7r/2jIByOJOfha2/xbzh/1UqkEMi+yfP2M4azLAR3XN8CdTVxyq9iZf5eSH+mLA5F3+Lm1H2fHyPA85+9ucjW/AKTmM/saRIJbbRwDPh/z/TICz87Z/P65L7FAYkn+09TirMZ36614fwhVmnICtPxO0xWoY6vep6eFbUfp+X0WYdjyXWqQs9kDJ2kFhPg03geEgo9PsFf8BadYTwu+tmxcV/H//Bn0ufbnnbLk+kqNRkWbFi3Tj9aYN9HLyYzK3SdywzW34f3XH9YLB2SpBSVQajXtFjwYv3bHD6jruI/PbSVUL0hUO0juAcEEBUoHa0JGIn4/8kXRbTpaNMA2QehLzQ8xdsWhNC4aGMlO0wWlj6JrhrfFUPY=
